### ISSUE TITLE
Autoload not working, when TPS is activated

### ISSUE THREAD

**Issue by Ben040Zin** [Courseplay/ToolPositionSaver_FS22#1]
[log.txt](https://github.com/Courseplay/ToolPositionSaver_FS22/files/7983822/log.txt)

Hallo.
Wenn TPS im Modordner ist, funktioniert Autoload (aPalletAutoLoader) nicht. Beim Drücken von R passiert nichts. Die Aktion wird auch nicht im F1-Menü angezeigt.

**Comment by rgoe** [comment]
Hallo Zusammen,
kann ich so bestätigen.
Karte: Elmcreek
Mods: nur aPalletautoloader,  Strautmann SEK802 Autoload, TPS (alles Modhub); Powertools

Bei aktiviertem TPS-mod ist die aPalletautoloader Specialization scheinbar deaktivert - Weder anzeige im F1-Menü noch lösen die Tasten eine Funktion aus.
TPS aktiviert:
![fsScreen_2022_02_02_13_23_00](https://user-images.githubusercontent.com/21224499/152170607-83697482-1254-4f5c-985f-3c34c64802c4.png)

TPS deaktiviert:
![fsScreen_2022_02_02_13_24_00](https://user-images.githubusercontent.com/21224499/152170651-2b3c8be2-134b-437a-bbdd-1b4065893899.png)

Das log ist unauffällig, keine error/warning diesbzgl.
[log.txt](https://github.com/Courseplay/ToolPositionSaver_FS22/files/7987193/log.txt)

**Comment by CATSt0rm** [comment]
Bei mir gleicher Fehler wie von rgoe beschrieben.
