### ISSUE TITLE
Kleine anregung Funktion Aktivieren/Deaktivieren 

### ISSUE THREAD

**Issue by Aichinto** [Courseplay/ToolPositionSaver_FS22#11]
Servus,
erstmal danke das ihr die Funktion Umgesetzt habt !
Ich nutze sie fast nur noch, macht das spielen an Maus und Tastatur wesentlich angenehmer. 

Da ich die Funktion jetzt schon einige Wochen Teste, sind mir noch zwei Kleinigkeiten aufgefallen, bzw. Funktionen die ganz nützlich wären:

1. Aktivieren/Deaktiviern.
wäre es möglich die Funktion Per Tastenkombi zu aktivieren/deaktivieren ? 
Hintergrund hierzu ist dass ich meine 4 Positionen auf die Maus gelegt habe (LINKE / Rechte und Seitentasten).
Das ganze funktioniert super wenn man z.b. monoton BGA befüllt, muss man dann aber z.b etwas anderes machen kommen sich die festen tasten und die Mausbedienung etwas in die Quere. (manchmal geht's ganz gut das man dann mit gedrückter taste trotzdem den arm bewegen kann)

2. Speichern  Werkzeuge.
Der zweite punkt wäre das man die Gespeicherten Positionen dem Werkzeug und nicht dem Lader zugewiesen werden. 
würde das Lästige löschen und neu vergeben der Positionen ersparen. 

Allerdings denke ich das dass so kaum bis gar nicht umsetzbar ist, aber ich wollts einfach mal ansprechen.

Vielen dank für eure große mühe !

**Comment by Tensuko** [comment]
Also 1 wäre sicher möglich, aber dann haben wir wieder eine weitere Tastenbelegung.... also nein das möchten wir nicht, auch wenn ich den Hintergrund verstehen kann.

Zu 2, siehe #12
