### ISSUE TITLE
Keine Tastenbelegung mehr im F1 Hilfefenster bei Patch 1.4.1

### ISSUE THREAD

**Issue by RumsdeBums** [Courseplay/ToolPositionSaver_FS22#14]
Das Script funktioniert soweit wunderbar.
Nur wird keine Tastenbelegung im Hilfefenster angezeigt.

**Comment by txadi** [comment]
Hello, I have the same problem. I tested this mod alone and that works fine on 2 / 3 differents maps. But if Coursplay is active, only 2 lines appears. If autodrive is active too, nothing appears. There is no line in the help hud. But the script work well.

**Comment by Tensuko** [comment]
F1 Help Windows is very limited in what it can show.
Thats a basic game problem, like it have always been, to many actions, to less keybind possibilitys and to less space in F1 Menu.
