### ISSUE TITLE
Frontloader cannot be lifted/lowered with Bigbag Handler and attached Bigbag

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/ToolPositionSaver_FS22#2]
TPS creates problems with frontloader movement in combination with bigbag handler and attached bigbag. When bigbag is attached the camera moves instead of the front loader - see video. Also the tool selection does not work anymore (the bigbag stays selected).

TPS is the only active mod in saved game.

https://user-images.githubusercontent.com/76711921/152234932-bcce137e-8492-47d3-b213-d3e97f1612d8.mp4

Extract from log:
2022-02-02 21:44 Error: Running LUA method 'update'.
J:/Eigene Dokumente/My Games/FarmingSimulator2022/mods/FS22_ToolPositionSaver/ToolPositionSaver.lua:200: attempt to index field 'spec_cylindered' (a nil value)

Thanks for the great work on the FS scripts!

**Comment by Tensuko** [comment]
Oh yea I guess I know whats the problem here.
Thanks, will have a look.
