### ISSUE TITLE
TPS doesn't work with standard giant forkelifts

### ISSUE THREAD

**Issue by CATSt0rm** [Courseplay/ToolPositionSaver_FS22#4]
Bei den im LS22 enthaltenen Standardgabelstaplern funktioniert TPS nicht. Die Tastenkombinationen werden im Help angezeigt und nach dem Speichern der Position(en) springt die Anzeige auch entsprechend um. Allerdings werden die Positionen nicht angefahren.

**Comment by Tensuko** [comment]
Hm, muss ich irgendwann mal probieren.
