### ISSUE TITLE
Mod conflict with Pallet Autoloader Specialization Mod

### ISSUE THREAD

**Issue by Elite82pt** [Courseplay/ToolPositionSaver_FS22#5]
So when your mod is enabled the Pallet Autoloader Specialization stops working...

**Comment by Pointer-de** [comment]
Same here. I've uploaded my log and some screenshots in the off. FS-Forum: https://forum.giants-software.com/viewtopic.php?p=1478410#p1478410

**Comment by Tensuko** [comment]
Strange but yea we will have a look.

**Comment by Tensuko** [comment]
#1 duplicate
