### ISSUE TITLE
[InfroFromDev] Changelog 1.0.1.0

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/ToolPositionSaver_FS22#6]
Will be sent to ModHub today.

Changelog 1.0.1.0:
- Works now with Forkelifts
- Fixed mod compatibility Issue with FS22_cultivatorFieldCreator
- Fixed mod compatibility Issue with FS22_aPalletAutoLoader
- Fixed Issue with Bigbag Handler
- Added keybind to show/hide the keybinds

**Comment by xBreezy1x** [comment]
Would it be possible to just add a **Tool Position Indicator** (degrees of tilt and height above ground) to our HUDs? This is SUPER HELPFUL for those of us who use joysticks to operate front loaders, wheel loaders, and forklifts from in-cab!

**Comment by Tensuko** [comment]
See #8
