### ISSUE TITLE
[BUG] Train is not working

### ISSUE THREAD

**Issue by Joachim-LS** [Courseplay/ToolPositionSaver_FS22#7]
If ToolPositionSaver (version 1.0.0.0) is active, you could not change the wagons at the train and unload them manually. Also there is a lua-Error

```
Error: Running LUA method 'update'.
C:/Users/----/Documents/My Games/FarmingSimulator2022/mods/FS22_ToolPositionSaver/ToolPositionSaver.lua:200: attempt to index field 'spec_cylindered' (a nil value)
```

[log.txt](https://github.com/Courseplay/ToolPositionSaver_FS22/files/8088265/log.txt)
![fsScreen_2022_02_17_12_21_31](https://user-images.githubusercontent.com/99879809/154472986-7d12e68e-1d24-4009-9308-6931bb1865b9.png)

With pressing `g` it is not possible to switch.

I found this in my savegame, deactivating of ToolPositionSaver and everything is fine. For explore this bug, i started with only one mod in modfolder and a new Haut-Beyleron Savegame.

**Comment by Tensuko** [comment]
Can you try the Updated Version (download master branch)

**Comment by Joachim-LS** [comment]
sorry for posting this issue. In Version 1.0.1.0 everything is fine with the train.

thanks for your work.
