### ISSUE TITLE
LUA Script Problem with Low Loader

### ISSUE THREAD

**Issue by m-tanguay** [Courseplay/ToolPositionSaver_FS22#9]
Hi Guys!

Been happening to be in the last few days.
If I purchase Any Low Loader or trailer.
Tool Position Saver Goes in a LUA Script LOOP
Forces me to FORCE EXIT the game since no keyboard/controller reacts anymore.

Here is the LOG FIlE
[log.txt](https://github.com/Courseplay/ToolPositionSaver_FS22/files/8146951/log.txt)

**Comment by Tensuko** [comment]
Becourse you use the old version.
